"""create stock forecast table

Revision ID: de028c828ca3
Revises: b47f46f5a546
Create Date: 2025-03-28 20:05:03.175361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de028c828ca3'
down_revision = 'b47f46f5a546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('retrieved_data', sa.Text(), nullable=False),
    sa.Column('forecast', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_forecasts')
    # ### end Alembic commands ###
